### ISSUE TITLE
Switching tabs on iPhone does not work.

### ISSUE THREAD

**Issue by meirege** [BartDelrue/allieTabs#1]
We're having an issue on different types of iPhones.

When clicking a tab on iPhone it does not change tabs. After clicking a second time it does change tabs.

**Comment by BartDelrue** [comment]
Hi @meirege 

Thank you for using allieTabs!

This is a safari mobile issue, caused by using hover styling on the tab elements.
Move all hover styling to the following media query and you should be fine:

`@media (hover), (-ms-high-contrast: none), (-ms-high-contrast: active) { }`

I have updated the demo site accordingly.

Please let me know if you have any more issues.
